services:
  bomba-infusao:
      container_name: ${APP_NAME:-bomba-infusao}-${ENV_NAME:-dev}
      image: ${APP_NAME:-bomba-infusao}:${ENV_NAME:-dev}
      build:
        context: ./bomba-infusao
        dockerfile: ./Dockerfile
        args:
          APP_NAME: ${APP_NAME:-bomba-infusao}
          ENV_NAME: ${ENV_NAME:-dev}
      ports:
        - "${SINAIS_VITAIS_PORT:-7002}:8000"
      volumes:
        - ./bomba-infusao:/usr/app
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT:-7002}/health || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 5
      networks:
        - uti-monitor-sinais-vitais_projeto_uti

networks:
  uti-monitor-sinais-vitais_projeto_uti:
    external: true