name: Docker Image CI

on:
  push:
    branches: [ "main", "rafaellopesbr-patch-1" ]
  pull_request:
    branches: [ "main", "rafaellopesbr-patch-1" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        ls -la
        pwd
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
